Repository Team-Ampersand/GKR-Android, pull requests merged in 2023-07, with the labels that each got.

#45 🔀 :: (#42) Feature - write navigation logic
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mpersand/gkr_android/GKRAdminNavHost.kt
  app/src/main/java/com/mpersand/gkr_android/MainActivity.kt
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/mpersand/presentation/view/signin/navigation/SignInNavigation.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#46 🔀 :: (#44) Feature - search publishing
  buildSrc/src/main/java/Dependency.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/mpersand/presentation/view/search/SearchScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/search/component/SearchHistoryItem.kt
  presentation/src/main/java/com/mpersand/presentation/view/search/component/SearchResultItem.kt
  presentation/src/main/res/drawable/diagonal_arrow.png
  presentation/src/main/res/drawable/history_icon.png
  presentation/src/main/res/drawable/rignt_arrow.png
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#49 🔀 :: (#48) Feature - modify signin view overlapping
  presentation/src/main/java/com/mpersand/presentation/view/signin/SignInScreen.kt
Labels: 1️⃣ Priority: High, 🐞 Type: Bug

#51 🔀 :: (#50) Feature - delete header
  data/src/main/java/com/mpersand/data/network/api/AuthApi.kt
  data/src/main/java/com/mpersand/data/network/api/EquipmentApi.kt
  data/src/main/java/com/mpersand/data/network/api/OrderApi.kt
  data/src/main/java/com/mpersand/data/network/api/RepairApi.kt
  data/src/main/java/com/mpersand/data/network/api/UserApi.kt
  data/src/main/java/com/mpersand/data/network/api/ViolationApi.kt
Labels: 1️⃣ Priority: High, 🔨 Type: Refector

#53 🔀 :: (#52) write main page data logic
  data/src/main/java/com/mpersand/data/remote/datasource/equipment/EquipmentDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/equipment/EquipmentDataSourceImpl.kt
  di/src/main/java/com/mpersand/di/modules/RemoteDataSourceModule.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#55 🔀 :: (#54) Feature - write main page domain logic
  data/src/main/java/com/mpersand/data/dto/auth/request/SignInRequest.kt
  data/src/main/java/com/mpersand/data/dto/auth/response/SignInResponse.kt
  data/src/main/java/com/mpersand/data/dto/order/response/EquipmentResponse.kt
  data/src/main/java/com/mpersand/data/dto/repair/request/RepairRequest.kt
  data/src/main/java/com/mpersand/data/dto/repair/response/RepairResponse.kt
  data/src/main/java/com/mpersand/data/dto/user/response/UserResponse.kt
  data/src/main/java/com/mpersand/data/dto/violation/request/ViolationRequest.kt
  data/src/main/java/com/mpersand/data/dto/violation/response/ViolationResponse.kt
  data/src/main/java/com/mpersand/data/network/api/AuthApi.kt
  data/src/main/java/com/mpersand/data/network/api/RepairApi.kt
  data/src/main/java/com/mpersand/data/network/api/UserApi.kt
  data/src/main/java/com/mpersand/data/network/api/ViolationApi.kt
  data/src/main/java/com/mpersand/data/repository/AuthRepositoryImpl.kt
  data/src/main/java/com/mpersand/data/repository/EquipmentRepositoryImpl.kt
  data/src/test/java/com/mpersand/data/network/api/RepairApiTest.kt
  data/src/test/java/com/mpersand/data/network/api/ViolationApiTest.kt
  di/src/main/java/com/mpersand/di/modules/RepositoryModule.kt
  domain/src/main/java/com/mpersand/domain/model/auth/request/SignInRequestModel.kt
  domain/src/main/java/com/mpersand/domain/model/auth/response/SignInResponseModel.kt
  domain/src/main/java/com/mpersand/domain/model/equipment/response/EquipmentResponseModel.kt
  domain/src/main/java/com/mpersand/domain/model/response/SignInResponseModel.kt
  domain/src/main/java/com/mpersand/domain/repository/AuthRepository.kt
  domain/src/main/java/com/mpersand/domain/repository/EquipmentRepository.kt
  domain/src/main/java/com/mpersand/domain/usecase/auth/SaveTokenUseCase.kt
  domain/src/main/java/com/mpersand/domain/usecase/auth/SignInUseCase.kt
  domain/src/main/java/com/mpersand/domain/usecase/equipment/GetAllEquipmentsUseCase.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/AuthViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#57 🔀 :: (#56) Feature - write main page viewmodel logic
  app/src/main/java/com/mpersand/gkr_android/GKRAdminNavHost.kt
  data/src/main/java/com/mpersand/data/repository/EquipmentRepositoryImpl.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/navigation/MainNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/view/signin/SignInScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/signin/navigation/SignInNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/AuthViewModel.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/MainViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#59 🔀 :: (#58) write detail page data logic
  data/src/main/java/com/mpersand/data/remote/datasource/equipment/EquipmentDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/equipment/EquipmentDataSourceImpl.kt
  data/src/main/java/com/mpersand/data/remote/datasource/order/OrderDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/order/OrderDataSourceImpl.kt
  di/src/main/java/com/mpersand/di/modules/RemoteDataSourceModule.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#63 🔀 :: (#62) Feature - write detail page viewmodel logic
  domain/src/main/java/com/mpersand/domain/usecase/equipment/GetEquipmentInfoUseCase.kt
  domain/src/main/java/com/mpersand/domain/usecase/order/PostRentalRequestUseCase.kt
  presentation/src/main/java/com/mpersand/presentation/view/detail/DetailScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/detail/navigation/DetailNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/DetailViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#65 🔀 :: (#64) Feature - write uistate and exception handling logic
  data/src/main/java/com/mpersand/data/remote/datasource/auth/AuthDataSourceImpl.kt
  data/src/main/java/com/mpersand/data/remote/datasource/equipment/EquipmentDataSourceImpl.kt
  data/src/main/java/com/mpersand/data/remote/datasource/order/OrderDataSourceImpl.kt
  data/src/main/java/com/mpersand/data/util/.gitkeep
  data/src/main/java/com/mpersand/data/util/SafeApiCall.kt
  domain/src/main/java/com/mpersand/domain/exception/HttpException.kt
  domain/src/main/java/com/mpersand/domain/exception/NoInternetException.kt
  presentation/src/main/java/com/mpersand/presentation/util/ExceptionHandling.kt
  presentation/src/main/java/com/mpersand/presentation/util/UiState.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/AuthViewModel.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/DetailViewModel.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/MainViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Type: Feature

#67 🔀 :: (#47) Feature - profile logic
  app/src/main/java/com/mpersand/gkr_android/GKRAdminNavHost.kt
  data/src/main/java/com/mpersand/data/dto/user/response/UserResponse.kt
  data/src/main/java/com/mpersand/data/remote/datasource/user/UserDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/user/UserDataSourceImpl.kt
  data/src/main/java/com/mpersand/data/repository/UserRepositoryImpl.kt
  di/src/main/java/com/mpersand/di/modules/RemoteDataSourceModule.kt
  di/src/main/java/com/mpersand/di/modules/RepositoryModule.kt
  domain/src/main/java/com/mpersand/domain/model/response/UserResponseModel.kt
  domain/src/main/java/com/mpersand/domain/repository/UserRepository.kt
  domain/src/main/java/com/mpersand/domain/usecase/user/GetUserUseCase.kt
  domain/src/main/java/com/mpersand/domain/usecase/user/LogoutUseCase.kt
  presentation/src/main/java/com/mpersand/presentation/view/component/GKRToolbar.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/navigation/MainNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/view/profile/ProfileScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/profile/component/dialog/LogoutDialog.kt
  presentation/src/main/java/com/mpersand/presentation/view/profile/navigation/ProfileNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/view/search/SearchScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/search/component/SearchHistoryItem.kt
  presentation/src/main/java/com/mpersand/presentation/view/signin/navigation/SignInNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/UserViewModel.kt
  presentation/src/main/res/drawable/diagonal_arrow.png
  presentation/src/main/res/drawable/history_icon.png
  presentation/src/main/res/drawable/ic_diagonal_arrow.xml
  presentation/src/main/res/drawable/ic_history_icon.xml
  presentation/src/main/res/drawable/ic_right_arrow.xml
  presentation/src/main/res/drawable/rignt_arrow.png
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#68 🔀 :: (#66) Feature - write navigation logic
  app/src/main/java/com/mpersand/gkr_android/GKRAdminNavHost.kt
  presentation/src/main/java/com/mpersand/presentation/view/detail/navigation/DetailNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/navigation/MainNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/view/signin/SignInScreen.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/AuthViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#72 🔀 :: (#71) Refactoring - profile uistate and exception handling logic
  data/src/main/java/com/mpersand/data/remote/datasource/user/UserDataSourceImpl.kt
  presentation/src/main/java/com/mpersand/presentation/view/profile/ProfileScreen.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/UserViewModel.kt
Labels: 1️⃣ Priority: High, 🪛 Type: Performance

#74 🔀 :: (#73) Refactoring - equipment filter click logic
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/component/GKRFilterItem.kt
Labels: 1️⃣ Priority: High, 🪛 Type: Performance

#77 🔀 :: (#75) Feature - get equipment list by user
  data/src/main/java/com/mpersand/data/remote/datasource/order/OrderDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/order/OrderDataSourceImpl.kt
  data/src/main/java/com/mpersand/data/repository/OrderRepositoryImpl.kt
  domain/src/main/java/com/mpersand/domain/repository/OrderRepository.kt
  domain/src/main/java/com/mpersand/domain/usecase/order/EquipmentRentalByUserUseCase.kt
  presentation/src/main/java/com/mpersand/presentation/view/profile/ProfileScreen.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/ProfileViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#81 🔀 :: (#80) Feature - write snack bar error handling
  presentation/src/main/java/com/mpersand/presentation/view/detail/DetailScreen.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#84 🔀 :: (#83) Feature - search logic
  app/src/main/java/com/mpersand/gkr_android/GKRAdminNavHost.kt
  data/src/main/java/com/mpersand/data/remote/datasource/equipment/EquipmentDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/equipment/EquipmentDataSourceImpl.kt
  data/src/main/java/com/mpersand/data/repository/EquipmentRepositoryImpl.kt
  domain/src/main/java/com/mpersand/domain/repository/EquipmentRepository.kt
  domain/src/main/java/com/mpersand/domain/usecase/equipment/EquipmentFilterUseCase.kt
  presentation/src/main/java/com/mpersand/presentation/view/component/GKRToolbar.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/navigation/MainNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/view/search/SearchScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/search/component/SearchHistoryItem.kt
  presentation/src/main/java/com/mpersand/presentation/view/search/component/SearchResultItem.kt
  presentation/src/main/java/com/mpersand/presentation/view/search/navigation/SearchNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/SearchViewModel.kt
  presentation/src/main/res/drawable/ic_search.xml
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#86 🔀 :: (#85) Feature - main filter viewmodel logic
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/MainViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#92 🔀 :: (#88) Feature - write navigation drawer profile logic
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/MainViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#93 🔀 :: (#91) Fix - profile rent lise bug
  presentation/src/main/java/com/mpersand/presentation/view/profile/ProfileScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/profile/component/RentEquipmentItem.kt
Labels: 0️⃣ Priority: Critical, 🐞 Type: Bug

#96 🔀 :: (#95) Feature - search result list navigation logic
  app/src/main/java/com/mpersand/gkr_android/GKRAdminNavHost.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/profile/ProfileScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/search/SearchScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/search/component/SearchResultItem.kt
  presentation/src/main/java/com/mpersand/presentation/view/search/navigation/SearchNavigation.kt
Labels: 0️⃣ Priority: Critical, ✨ Type: Feature

#98 🔀 :: (#97) rental snack bar bug
  presentation/src/main/java/com/mpersand/presentation/view/detail/DetailDialog.kt
  presentation/src/main/java/com/mpersand/presentation/view/detail/DetailScreen.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/DetailViewModel.kt
Labels: 0️⃣ Priority: Critical, 🐞 Type: Bug

#100 🔀 :: (#99) Feature - custom clickable
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/modifier/GKRClickable.kt
  presentation/src/main/java/com/mpersand/presentation/view/search/component/SearchResultItem.kt
Labels: 2️⃣ Priortiy: Medium, ✨ Type: Feature

#103 🔀 :: (#102) Feature - write auto login logic
  data/src/main/java/com/mpersand/data/local/datasource/LocalDataSource.kt
  data/src/main/java/com/mpersand/data/local/datasource/LocalDataSourceImpl.kt
  data/src/main/java/com/mpersand/data/repository/AuthRepositoryImpl.kt
  data/src/main/java/com/mpersand/data/repository/UserRepositoryImpl.kt
  domain/src/main/java/com/mpersand/domain/repository/AuthRepository.kt
  domain/src/main/java/com/mpersand/domain/usecase/auth/IsLoginUseCase.kt
  presentation/src/main/java/com/mpersand/presentation/view/signin/SignInScreen.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/AuthViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#105 🔀 :: (#104) FIx - profile logic fix
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/profile/ProfileScreen.kt
Labels: 0️⃣ Priority: Critical, 🐞 Type: Bug

#107 🔀 :: (#106) FIx - search logic fix
  presentation/src/main/java/com/mpersand/presentation/view/search/SearchScreen.kt
Labels: 0️⃣ Priority: Critical, 🐞 Type: Bug
