Repository Team-Ampersand/GKR-Android, pull requests merged in 2023-06, with the labels that each got.

#11 🔀 :: (#9) Feature - write auth remote logic
  .github/workflows/android.yml
  data/build.gradle.kts
  data/src/main/java/com/mpersand/data/dto/.gitkeep
  data/src/main/java/com/mpersand/data/dto/request/SignInRequest.kt
  data/src/main/java/com/mpersand/data/dto/response/ReissueTokenResponse.kt
  data/src/main/java/com/mpersand/data/dto/response/SignInResponse.kt
  data/src/main/java/com/mpersand/data/network/api/.gitkeep
  data/src/main/java/com/mpersand/data/network/api/AuthApi.kt
  data/src/test/java/com/mpersand/data/ExampleUnitTest.kt
  data/src/test/java/com/mpersand/data/network/api/AuthApiTest.kt
  di/src/main/java/com/mpersand/di/modules/NetworkModule.kt
Labels: 1️⃣ Priority: High, 📬 Type: API

#13 🔀 :: (#10) Feature - write order remote logic
  data/build.gradle.kts
  data/src/main/java/com/mpersand/data/dto/order/request/ExtensionRequest.kt
  data/src/main/java/com/mpersand/data/dto/order/request/OrderRequest.kt
  data/src/main/java/com/mpersand/data/dto/order/request/ResultRequest.kt
  data/src/main/java/com/mpersand/data/dto/order/response/EquipmentResponse.kt
  data/src/main/java/com/mpersand/data/dto/order/response/OrderResponse.kt
  data/src/main/java/com/mpersand/data/dto/order/response/UserResponse.kt
  data/src/main/java/com/mpersand/data/network/api/OrderApi.kt
  data/src/test/java/com/mpersand/data/network/api/OrderApiTest.kt
  di/src/main/java/com/mpersand/di/modules/NetworkModule.kt
Labels: 1️⃣ Priority: High, 📬 Type: API

#17 🔀 :: (#14) Feature - equipment remote logic
  data/src/main/java/com/mpersand/data/dto/equipment/request/EquipmentRequest.kt
  data/src/main/java/com/mpersand/data/dto/equipment/request/ModifyEquipmentRequest.kt
  data/src/main/java/com/mpersand/data/network/api/EquipmentApi.kt
  data/src/test/java/com/mpersand/data/network/api/EquipmentApiTest.kt
Labels: 1️⃣ Priority: High, 📬 Type: API

#18 🔀 :: (#16) Feature - write repair remote logic
  data/src/main/java/com/mpersand/data/dto/request/RepairRequest.kt
  data/src/main/java/com/mpersand/data/dto/response/RepairResponse.kt
  data/src/main/java/com/mpersand/data/network/api/RepairApi.kt
  data/src/test/java/com/mpersand/data/network/api/RepairApiTest.kt
Labels: 1️⃣ Priority: High, 📬 Type: API

#20 🔀 :: (#19) Feature - write violation remote logic
  data/src/main/java/com/mpersand/data/dto/request/ViolationRequest.kt
  data/src/main/java/com/mpersand/data/dto/response/ViolationResponse.kt
  data/src/main/java/com/mpersand/data/network/api/ViolationApi.kt
  data/src/test/java/com/mpersand/data/network/api/ViolationApiTest.kt
  di/src/main/java/com/mpersand/di/modules/NetworkModule.kt
Labels: 1️⃣ Priority: High, 📬 Type: API

#22 🔀 :: (#21) Feature - signin screen publishing
  .gitignore
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/mpersand/presentation/view/.gitkeep
  presentation/src/main/java/com/mpersand/presentation/view/SignInScreen.kt
  presentation/src/main/res/drawable/ic_logo.xml
  presentation/src/main/res/font/fraunces_black.ttf
  settings.gradle.kts
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#24 🔀 :: (#23) Feature - write auth data logic
  data/src/main/java/com/mpersand/data/remote/datasource/.gitkeep
  data/src/main/java/com/mpersand/data/remote/datasource/auth/AuthDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/auth/AuthDataSourceImpl.kt
  di/src/main/java/com/mpersand/di/modules/RemoteDataSourceModule.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#26 🔀 :: (#25) Feature - write auth domain logic
  data/src/main/java/com/mpersand/data/dto/auth/request/SignInRequest.kt
  data/src/main/java/com/mpersand/data/dto/auth/response/SignInResponse.kt
  data/src/main/java/com/mpersand/data/dto/request/SignInRequest.kt
  data/src/main/java/com/mpersand/data/network/api/AuthApi.kt
  data/src/main/java/com/mpersand/data/remote/datasource/auth/AuthDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/auth/AuthDataSourceImpl.kt
  data/src/main/java/com/mpersand/data/repository/.gitkeep
  data/src/main/java/com/mpersand/data/repository/AuthRepositoryImpl.kt
  data/src/test/java/com/mpersand/data/network/api/AuthApiTest.kt
  di/src/main/java/com/mpersand/di/modules/RepositoryModule.kt
  domain/build.gradle.kts
  domain/src/main/java/com/mpersand/domain/model/.gitkeep
  domain/src/main/java/com/mpersand/domain/model/request/SignInRequestModel.kt
  domain/src/main/java/com/mpersand/domain/model/response/SignInResponseModel.kt
  domain/src/main/java/com/mpersand/domain/repository/.gitkeep
  domain/src/main/java/com/mpersand/domain/repository/AuthRepository.kt
  domain/src/main/java/com/mpersand/domain/usecase/.gitkeep
  domain/src/main/java/com/mpersand/domain/usecase/SignInUseCase.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#28 🔀 :: (#27) Feature - write auth viewmodel logic
  .github/workflows/android.yml
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  domain/src/main/java/com/mpersand/domain/usecase/SignInUseCase.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/mpersand/presentation/view/SignInScreen.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/.gitkeep
  presentation/src/main/java/com/mpersand/presentation/viewmodel/AuthViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#30 🔀 :: (#29) Feature - write token interceptor logic
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  data/build.gradle.kts
  data/src/main/java/com/mpersand/data/local/datasource/.gitkeep
  data/src/main/java/com/mpersand/data/local/datasource/LocalDataSource.kt
  data/src/main/java/com/mpersand/data/local/datasource/LocalDataSourceImpl.kt
  data/src/main/java/com/mpersand/data/network/RequestInterceptor.kt
  data/src/main/java/com/mpersand/data/repository/AuthRepositoryImpl.kt
  di/src/main/java/com/mpersand/di/modules/LocalDataSourceModule.kt
  di/src/main/java/com/mpersand/di/modules/NetworkModule.kt
  domain/src/main/java/com/mpersand/domain/exception/.gitkeep
  domain/src/main/java/com/mpersand/domain/exception/TokenExpiredException.kt
  domain/src/main/java/com/mpersand/domain/repository/AuthRepository.kt
  domain/src/main/java/com/mpersand/domain/usecase/SaveTokenUseCase.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/AuthViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#35 🔀 :: (#34) Feature - write network module di logic
  di/src/main/java/com/mpersand/di/modules/NetworkModule.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#38 🔀 :: (#36) Feature - profile screen publishing
  presentation/src/main/java/com/mpersand/presentation/view/component/GKRToolbar.kt
  presentation/src/main/java/com/mpersand/presentation/view/profile/ProfileScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/profile/component/BanHistoryItem.kt
  presentation/src/main/java/com/mpersand/presentation/view/profile/component/RentEquipmentItem.kt
  presentation/src/main/java/com/mpersand/presentation/view/profile/component/dialog/LogoutDialog.kt
  presentation/src/main/java/com/mpersand/presentation/view/signin/SignInScreen.kt
  presentation/src/main/res/drawable/ic_temp_equipment_image.png
  presentation/src/main/res/drawable/ic_user_image.xml
  presentation/src/main/res/font/inter_black.ttf
  presentation/src/main/res/font/inter_light.ttf
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#37 🔀 :: (#31) main screen publishing
  .gitignore
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/mpersand/presentation/view/MainScreen.kt
  presentation/src/main/res/drawable/ic_bell.xml
  presentation/src/main/res/drawable/ic_folder.xml
  presentation/src/main/res/drawable/ic_hamburger.xml
  presentation/src/main/res/drawable/ic_handshake.xml
  presentation/src/main/res/drawable/ic_profile.xml
  presentation/src/main/res/drawable/ic_search.xml
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#41 🔀 :: Feature - (#39) detail screen publishing
  presentation/src/main/java/com/mpersand/presentation/view/detail/DetailDialog.kt
  presentation/src/main/java/com/mpersand/presentation/view/detail/DetailScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#43 🔀 :: (#40) Feature - equipment filter publishing
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/component/GKRFilterItem.kt
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing
